services:
  - environment_slug: node-js
    name: backend
    source:
      type: github
      repo: mimsou/growthai_back_end
      branch: master
    
    build_command: npm install && npm run build
    run_command: npm run start:prod
    http_port: 3001
    routes:
      - path: /api
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: your-database-url
      - key: PORT
        value: "3001"
  - environment_slug: node-js
    name: frontend
    source:
      type: github
      repo: mimsou/growthai_front_end
      branch: master

    build_command: npm install && npm run build
    run_command: npx serve -s build
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: REACT_APP_API_URL
        value: https://api.mydomain.com
